# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "CLI client for Mittwald SPACES"
  homepage "https://www.spaces.de/"
  version "1.12.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mittwald/spacectl/releases/download/v1.12.2/spacectl_1.12.2_darwin_amd64.tar.gz"
    sha256 "e7902071b4f2fb52a89f05c536a6cefe5f62835d51a8292fb1707972c45edeb5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mittwald/spacectl/releases/download/v1.12.2/spacectl_1.12.2_linux_amd64.tar.gz"
      sha256 "dd576e55295dc7020f225960853001b444e08ab13ace7ce47b431340c5d73ec0"
    end
  end

  def install
    bin.install "spacectl"
  end
end
