# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "CLI client for Mittwald SPACES"
  homepage "https://www.spaces.de/"
  url "https://github.com/mittwald/spacectl/releases/download/v1.11.7/spacectl_1.11.7_darwin_amd64.tar.gz"
  version "1.11.7"
  sha256 "b8319e60e38196137eb1f24356399bf5d4051627c23d8ad4effb918f6b9ba5e6"

  def install
    bin.install "spacectl"
  end
end
